import {bibleUnits,pdfUnits,makeContext,safeModel,splitText} from './core.mjs';
import * as db from './storage.mjs';
import {explain,recognize,listModels} from './gemini.mjs';
import {Speaker} from './speaker.mjs';
import {importPDF,renderPage} from './pdf.mjs';

const $=id=>document.getElementById(id);
const defaults={textModel:'gemini-2.5-flash',ttsModel:'gemini-2.5-flash-preview-tts',geminiVoice:'Kore',voiceMode:'auto',phoneVoice:'',speechRate:1,fontSize:20,speakAnswers:true};
const readLocal=(k,fallback)=>{try{return JSON.parse(localStorage.getItem(k))??fallback;}catch{return fallback;}};
let cfg={...defaults,...readLocal('lc-config',{})};
let apiKey='';try{apiKey=localStorage.getItem('lc-key')||sessionStorage.getItem('lc-session-key')||'';}catch{}
let bible,activeBook,study=null,units=[],index=0,mark={},running=false,readingEpoch=0,advanceOnResume=false,completed=false;
let lastStudy=null,pdfBooks=[],chat=[],chatId='',questionContext='',questionSource=null,askController=null,questionEpoch=0,recognition=null;
let wakeLock=null,renderedStart=-1,lastSave=0,saveWarning=false,pdfRendering=false;
const notice=(message,error=false)=>{const n=$('notice');n.textContent=message;n.className='notice'+(error?' error':'');n.hidden=!message;};
let toastTimer;function toast(message){const host=document.querySelector('dialog[open]')||document.body;host.appendChild($('toast'));$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5500);}
const on=(id,event,fn)=>$(id).addEventListener(event,e=>{Promise.resolve().then(()=>fn(e)).catch(err=>{if(err.name!=='AbortError')notice(err.message||'Não foi possível concluir esta ação.',true);});});
const speaker=new Speaker(()=>cfg,()=>apiKey,(status,voice)=>{if(running){$('playerStatus').textContent=status;$('voiceStatus').textContent=voice;}},(message,automatic)=>{
  $('phoneFallback').hidden=automatic;
  if(automatic){notice('A voz Gemini ficou indisponível. Continuamos com a voz do celular; as explicações continuam usando o modelo de texto. Se a troca ocorreu no meio de uma parte, ela será relida.');$('voiceStatus').textContent='Voz do celular';}
  else notice(message,true);
});
function newOption(value,label){const o=document.createElement('option');o.value=value;o.textContent=label;return o;}
function fillSelect(el,items,value){el.replaceChildren(...items.map(x=>newOption(x.value??x,x.label??x)));if(value!==undefined)el.value=String(value);}
function selectedBible(){return bible.books.find(b=>b.id===$('bibleBook').value)||bible.books[0];}
function chapterOptions(reset=false){const b=selectedBible();const list=b.chapters.map((_,i)=>i+1);const a=reset?1:Math.min(Number($('startChapter').value)||1,list.length);const z=reset?1:Math.max(a,Math.min(Number($('endChapter').value)||a,list.length));fillSelect($('startChapter'),list,a);fillSelect($('endChapter'),list,z);verseOptions('start',true);verseOptions('end',true);}
function verseOptions(side,reset=false){const b=selectedBible(),ch=Number($(side+'Chapter').value)||1;const arr=(b.chapters[ch-1]||[]).map(v=>v.n);const prev=Number($(side+'Verse').value);fillSelect($(side+'Verse'),arr,!reset&&arr.includes(prev)?prev:side==='start'?arr[0]:arr.at(-1));}
function selectSource(kind){$('biblePanel').hidden=kind!=='bible';$('pdfPanel').hidden=kind!=='pdf';$('bibleTab').setAttribute('aria-selected',String(kind==='bible'));$('pdfTab').setAttribute('aria-selected',String(kind==='pdf'));}
function updateVoiceLabel(){const usePhone=cfg.voiceMode==='phone'||speaker.usePhone||!apiKey;$('voiceStatus').textContent=usePhone?'Voz do celular':'Voz Gemini';}
function positionRecord(){return {id:'last',...study,index,mark:{...mark},advanceOnResume,completed,studyMode:$('studyMode').value,updated:Date.now()};}
async function savePosition(force=false){if(!study)return;if(!force&&Date.now()-lastSave<2500)return;lastSave=Date.now();const record=positionRecord();lastStudy=record;updateResumeCard();try{await db.put('state',record);await db.put('state',{...record,id:'progress:'+study.bookId});}catch{if(!saveWarning){saveWarning=true;notice('O navegador não conseguiu salvar o progresso. Verifique o espaço do aparelho e evite a navegação anônima.',true);}}}
function updateResumeCard(){if(!lastStudy)return;$('lastStudy').hidden=false;$('lastStudyLabel').textContent=lastStudy.title||'Última leitura';}
async function keepScreen(){try{if('wakeLock'in navigator&&!wakeLock)wakeLock=await navigator.wakeLock.request('screen');}catch{}}
async function releaseScreen(){try{await wakeLock?.release();}catch{}wakeLock=null;}
function pauseReading(){readingEpoch++;if(running){mark=speaker.stop();running=false;}else speaker.stop();$('playPause').textContent=completed?'Ouvir novamente':'Continuar leitura';$('playerStatus').textContent=completed?'Trecho concluído':'Leitura pausada';void savePosition(true);void releaseScreen();}
function stopQuestion(){questionEpoch++;askController?.abort();askController=null;recognition?.stop();recognition=null;$('sendQuestion').disabled=false;$('sendQuestion').textContent='Perguntar ao Gemini';$('cancelQuestion').hidden=true;speaker.stop();}
async function activate(desc,{restore=false}={}){
 pauseReading();stopQuestion();if($('questionDialog').open)$('questionDialog').close();
 const book=desc.kind==='bible'?bible.books.find(x=>x.id===desc.bookId):await db.get('books',desc.bookId);
 if(!book)throw new Error('Este livro não está neste aparelho. Adicione novamente o PDF.');
 const list=desc.kind==='bible'?bibleUnits(book,desc.startChapter,desc.startVerse,desc.endChapter,desc.endVerse):pdfUnits(book,desc.startPage,desc.endPage);
 if(!list.length)throw new Error('Este intervalo não contém texto para estudar.');
 activeBook=book;units=list;study={...desc};delete study.mark;delete study.index;delete study.id;index=restore?Math.min(Math.max(0,desc.index||0),units.length-1):0;mark=restore?desc.mark||{}:{};advanceOnResume=restore?!!desc.advanceOnResume:false;completed=restore?!!desc.completed:false;renderedStart=-1;
 selectSource(desc.kind);
 if(desc.kind==='bible'){$('bibleBook').value=book.id;chapterOptions(true);$('startChapter').value=desc.startChapter;$('endChapter').value=desc.endChapter;verseOptions('start',true);verseOptions('end',true);$('startVerse').value=desc.startVerse;$('endVerse').value=desc.endVerse;}
 else{$('pdfBook').value=book.id;pdfRangeChanged();$('pdfStart').value=desc.startPage;$('pdfEnd').value=desc.endPage;}
 $('studyMode').value=restore&&desc.studyMode?desc.studyMode:'read';$('readingTitle').textContent=desc.title;$('readingKicker').textContent=desc.kind==='bible'?'BÍBLIA LIVRE · PORTUGUÊS':book.name;$('completed').hidden=!completed;
 $('playPause').textContent=completed?'Ouvir novamente':restore?'Continuar leitura':'Ouvir leitura';$('playerStatus').textContent=completed?'Trecho concluído':'Pronto para ler';notice('');updateVoiceLabel();renderReader();await savePosition(true);
}
function renderReader(){
 if(!study)return;const start=Math.max(0,index-3),end=Math.min(units.length,index+18);const reader=$('reader');
 if(renderedStart!==start){const fragment=document.createDocumentFragment();for(let i=start;i<end;i++){const u=units[i],article=document.createElement('article');article.dataset.index=i;article.tabIndex=0;article.setAttribute('aria-label',u.ref+', selecionar este trecho');const ref=document.createElement('span');ref.className='chunk-ref';ref.textContent=u.ref+(u.part?' · continuação':'');const p=document.createElement('p');p.className='chunk-text';p.textContent=u.text||'Página sem texto selecionável. Abra a imagem original ou reconheça o texto com Gemini.';article.append(ref,p);article.addEventListener('click',()=>{pauseReading();index=i;mark={};advanceOnResume=false;completed=false;$('completed').hidden=true;renderReader();void savePosition(true);});article.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();article.click();}});fragment.append(article);}reader.replaceChildren(fragment);renderedStart=start;}
 for(const element of reader.querySelectorAll('article')){const active=Number(element.dataset.index)===index;element.classList.toggle('active',active);if(active)element.setAttribute('aria-current','true');else element.removeAttribute('aria-current');}
 $('positionLabel').textContent=`${units[index].ref} · parte ${index+1} de ${units.length}`;$('readingProgress').max=units.length;$('readingProgress').value=completed?units.length:index;
 $('previous').disabled=index===0;$('next').disabled=index===units.length-1;$('scanPanel').hidden=study.kind!=='pdf'||!!units[index].text;$('originalPanel').hidden=study.kind!=='pdf';if($('originalPanel').open)void showOriginal().catch(e=>notice(e.message,true));
 const selected=reader.querySelector('.active');if(selected&&selected.offsetTop-reader.offsetTop>reader.scrollTop+reader.clientHeight-100)reader.scrollTop=selected.offsetTop-reader.offsetTop-16;
}
async function playReading(){
 if(!study)return;stopQuestion();speaker.unlock();if($('questionDialog').open)$('questionDialog').close();
 if(completed){index=0;mark={};advanceOnResume=false;completed=false;$('completed').hidden=true;}
 if(advanceOnResume){advanceOnResume=false;index++;mark={};if(index>=units.length){index=units.length-1;finishReading();return;}}
 const epoch=++readingEpoch;running=true;$('playPause').textContent='Pausar leitura';await keepScreen();
 try{while(running&&epoch===readingEpoch){
   const u=units[index];renderReader();
   if(!u.text){pauseReading();notice('Esta página precisa de reconhecimento antes de ser narrada. Use o botão abaixo do texto.');return;}
   await speaker.say(u.text,{mark,onProgress:m=>{if(running&&epoch===readingEpoch){mark=m;void savePosition();}}});
   if(!running||epoch!==readingEpoch)return;
   mark={};const groupEnded=index===units.length-1||units[index+1].group!==u.group;
   if($('studyMode').value==='guided'&&groupEnded){running=false;advanceOnResume=true;readingEpoch++;speaker.stop();$('playPause').textContent='Continuar leitura';$('playerStatus').textContent='Pausa para a explicação';await savePosition(true);await releaseScreen();await openQuestion();await submitQuestion('Explique passo a passo a parte que acabei de ouvir, de forma simples e dentro do contexto. Aponte as referências e dê um exemplo quando ele ajudar.');return;}
   if(index===units.length-1){finishReading();return;}index++;await savePosition(true);
  }
 }catch(e){if(e.name!=='AbortError'&&epoch===readingEpoch){pauseReading();notice(e.message,true);}}
}
function finishReading(){running=false;readingEpoch++;speaker.stop();mark={};completed=true;advanceOnResume=false;$('completed').hidden=false;$('playPause').textContent='Ouvir novamente';$('playerStatus').textContent='Trecho concluído';$('readingProgress').value=units.length;void savePosition(true);void releaseScreen();}
function move(delta){pauseReading();index=Math.max(0,Math.min(units.length-1,index+delta));mark={};completed=false;advanceOnResume=false;$('completed').hidden=true;renderReader();void savePosition(true);}
async function openQuestion({summary=false}={}){
 if(!study)return;pauseReading();stopQuestion();const u=units[index];questionSource={kind:study.kind,book:activeBook,units:[...units],index,summary};
 questionContext=makeContext({...questionSource,question:'',summary});
 chatId=`${study.kind}:${study.bookId}:${summary?'summary:'+study.title:u.ref+':'+u.part}`;chat=(await db.get('chats',chatId))?.messages||[];
 $('questionLocation').textContent=summary?'Sessão: '+study.title:u.ref;$('questionExcerpt').textContent=summary?'Vamos rever o intervalo escolhido para esta sessão.':u.text||'Página ainda sem texto reconhecido.';renderChat();$('questionInput').value='';$('questionDialog').showModal();$('questionInput').focus();
}
function renderChat(){const container=$('conversation');container.replaceChildren();for(const message of chat){const d=document.createElement('div');d.className='message '+(message.role==='user'?'user':'assistant');const label=document.createElement('span');label.className='message-label';label.textContent=message.role==='user'?'VOCÊ':'EXPLICAÇÃO DO GEMINI';const p=document.createElement('p');p.textContent=message.text;d.append(label,p);if(message.role==='assistant'){const listen=document.createElement('button');listen.className='link-button';listen.textContent='Ouvir esta explicação';listen.addEventListener('click',()=>{speaker.unlock();void readAnswer(message.text).catch(e=>{if(e.name!=='AbortError')toast(e.message);});});d.append(listen);if(message.model){const meta=document.createElement('small');meta.textContent=message.model;d.append(meta);}}container.append(d);}container.scrollTop=container.scrollHeight;}
async function readAnswer(text){speaker.stop();for(const part of splitText(text.replace(/[*#`]/g,''),1500)){if(!$('questionDialog').open)return;await speaker.say(part);} }
async function submitQuestion(question){
 question=String(question||'').trim();if(!question||askController)return;
 if(!apiKey){toast('Primeiro, feche esta janela e adicione sua chave em Configurações.');return;}
 if(!questionSource)return;if(!units[index]?.text&&study.kind==='pdf'){toast('Reconheça o texto desta página primeiro.');return;}
 speaker.stop();const epoch=++questionEpoch;const controller=new AbortController();askController=controller;const history=chat.filter(m=>!m.error).slice(-8);const context=makeContext({...questionSource,question});
 chat.push({role:'user',text:question,date:Date.now()});renderChat();$('questionInput').value='';$('sendQuestion').disabled=true;$('cancelQuestion').hidden=false;$('sendQuestion').textContent='Preparando explicação…';
 try{const answer=await explain({key:apiKey,model:cfg.textModel,context,question,history,signal:controller.signal});if(epoch!==questionEpoch||controller.signal.aborted)return;
  const message={role:'assistant',text:answer.text,date:Date.now(),model:cfg.textModel};chat.push(message);renderChat();await db.put('chats',{id:chatId,messages:chat,bookId:study.bookId,ref:$('questionLocation').textContent}).catch(()=>toast('A resposta foi exibida, mas não pôde ser guardada neste aparelho.'));
  if(cfg.speakAnswers&&$('questionDialog').open&&epoch===questionEpoch)await readAnswer(answer.text);
 }catch(e){if(e.name!=='AbortError'&&epoch===questionEpoch){const message=document.createElement('p');message.className='notice error';message.textContent=e.message;$('conversation').append(message);$('conversation').scrollTop=$('conversation').scrollHeight;}}
 finally{if(epoch===questionEpoch){askController=null;$('sendQuestion').disabled=false;$('sendQuestion').textContent='Perguntar ao Gemini';$('cancelQuestion').hidden=true;}}
}
async function refreshPDFs(selected){pdfBooks=await db.all('books');fillSelect($('pdfBook'),[{value:'',label:pdfBooks.length?'Selecione um PDF':'Nenhum PDF adicionado'},...pdfBooks.map(b=>({value:b.id,label:b.name}))],selected||'');pdfRangeChanged();}
function pdfRangeChanged(){const b=pdfBooks.find(x=>x.id===$('pdfBook').value);$('pdfStart').max=b?.pages.length||1;$('pdfEnd').max=b?.pages.length||1;$('pdfStart').value=1;$('pdfEnd').value=b?Math.min(5,b.pages.length):1;$('openPdf').disabled=!b;$('deletePdf').disabled=!b;}
async function showOriginal(){if(pdfRendering||study?.kind!=='pdf')return;pdfRendering=true;const b=activeBook,p=units[index].page;try{const canvas=document.createElement('canvas');await renderPage(b,p,canvas);if(activeBook===b&&units[index]?.page===p){const target=$('pdfCanvas');target.width=canvas.width;target.height=canvas.height;target.getContext('2d').drawImage(canvas,0,0);}}finally{pdfRendering=false;if($('originalPanel').open&&study?.kind==='pdf'&&(activeBook!==b||units[index]?.page!==p))void showOriginal().catch(e=>notice(e.message,true));}}
function listPhoneVoices(){const previous=$('phoneVoice').value||cfg.phoneVoice;const v=window.speechSynthesis?.getVoices()||[];const ordered=[...v.filter(x=>/^pt/i.test(x.lang)),...v.filter(x=>!/^pt/i.test(x.lang))];fillSelect($('phoneVoice'),[{value:'',label:'Português automático'},...ordered.map(x=>({value:x.voiceURI,label:`${x.name} · ${x.lang}${x.localService?' · local':''}`}))],previous);}
function openSettings(){pauseReading();stopQuestion();if($('questionDialog').open)$('questionDialog').close();for(const name of Object.keys(defaults)){const el=$(name);if(el.type==='checkbox')el.checked=cfg[name];else el.value=cfg[name];}$('apiKey').value=apiKey;$('apiKey').type='password';$('showKey').textContent='Mostrar';try{$('rememberKey').checked=!!localStorage.getItem('lc-key');}catch{}listPhoneVoices();$('settingsDialog').showModal();void storageInfo();}
async function storageInfo(){try{const e=await navigator.storage?.estimate();const megabytes=e?Math.round(e.usage/1024/1024):null;$('storageInfo').textContent=megabytes!==null?`Espaço usado neste endereço: aproximadamente ${megabytes} MB.`:'Seu navegador guarda livros, conversas e áudios neste aparelho.';}catch{}}
function saveSettings(e){e.preventDefault();const next={};for(const name of Object.keys(defaults)){const el=$(name);next[name]=el.type==='checkbox'?el.checked:el.value;}
 safeModel(next.textModel);safeModel(next.ttsModel);next.speechRate=Number(next.speechRate);next.fontSize=Number(next.fontSize);cfg=next;apiKey=$('apiKey').value.trim();
 try{localStorage.setItem('lc-config',JSON.stringify(cfg));if($('rememberKey').checked&&apiKey){localStorage.setItem('lc-key',apiKey);sessionStorage.removeItem('lc-session-key');}else{localStorage.removeItem('lc-key');if(apiKey)sessionStorage.setItem('lc-session-key',apiKey);else sessionStorage.removeItem('lc-session-key');}}catch{toast('As configurações valem nesta sessão, mas o navegador não permitiu guardá-las.');}
 speaker.usePhone=false;$('phoneFallback').hidden=true;document.documentElement.style.setProperty('--reader-size',cfg.fontSize+'px');updateVoiceLabel();$('settingsDialog').close();toast('Configurações salvas.');}
async function loadAccountModels(){const key=$('apiKey').value.trim();if(!key){$('modelsStatus').textContent='Cole sua chave primeiro.';return;}$('loadModels').disabled=true;$('modelsStatus').textContent='Consultando os modelos da sua conta…';try{const models=await listModels(key);const names=models.map(m=>m.name.replace(/^models\//,''));const texts=names.filter(n=>!/(tts|image|live|audio|robot|computer-use)/i.test(n));const voices=names.filter(n=>/tts/i.test(n));$('textModels').replaceChildren(...texts.map(n=>newOption(n,n)));$('ttsModels').replaceChildren(...voices.map(n=>newOption(n,n)));if(!texts.includes($('textModel').value)&&texts.length)$('textModel').value=texts.find(n=>n==='gemini-2.5-flash')||texts.find(n=>/flash/.test(n))||texts[0];if(!voices.includes($('ttsModel').value)&&voices.length)$('ttsModel').value=voices.find(n=>n==='gemini-2.5-flash-preview-tts')||voices[0];$('modelsStatus').textContent=`Chave aceita. ${texts.length} modelos de texto e ${voices.length} de voz encontrados. A lista não informa quais têm cota gratuita; confira seu projeto no AI Studio.`;}catch(e){$('modelsStatus').textContent=e.message;}finally{$('loadModels').disabled=false;}}
function dictation(){
 const C=window.SpeechRecognition||window.webkitSpeechRecognition;if(!C){toast('Use o microfone do teclado do celular para ditar sua pergunta.');$('questionInput').focus();return;}
 if(recognition){recognition.stop();return;}speaker.stop();const rec=new C();recognition=rec;rec.lang='pt-BR';rec.interimResults=false;rec.continuous=false;$('dictate').textContent='Ouvindo… toque para parar';rec.onresult=e=>{$('questionInput').value=[$('questionInput').value,e.results[0][0].transcript].filter(Boolean).join(' ');};rec.onerror=()=>toast('Não foi possível usar o microfone. Você pode digitar ou usar o microfone do teclado.');rec.onend=()=>{recognition=null;$('dictate').textContent='Falar pergunta';};rec.start();
}
function download(name,blob){const a=document.createElement('a');const url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function toBase64(buffer){const b=new Uint8Array(buffer);let binary='';for(let i=0;i<b.length;i+=32768)binary+=String.fromCharCode(...b.subarray(i,i+32768));return btoa(binary);}
async function exportBackup(){pauseReading();const books=await db.all('books');const data={format:'livro-claro-backup',version:1,created:new Date().toISOString(),config:cfg,books:books.map(b=>({...b,bytes:toBase64(b.bytes)})),state:await db.all('state'),chats:await db.all('chats')};download('livro-claro-meus-estudos.json',new Blob([JSON.stringify(data)],{type:'application/json'}));toast('Cópia preparada. Guarde o arquivo em um local seguro.');}
async function restoreBackup(file){
 if(!file)return;if(file.size>240*1024*1024)throw new Error('A cópia é grande demais para restaurar neste navegador.');const d=JSON.parse(await file.text());
 if(d.format!=='livro-claro-backup'||d.version!==1||!Array.isArray(d.books)||!Array.isArray(d.state)||!Array.isArray(d.chats))throw new Error('Este arquivo não é uma cópia válida do Livro Claro.');
 const books=d.books.map(b=>{if(typeof b.id!=='string'||!b.id.startsWith('pdf-')||typeof b.name!=='string'||!Array.isArray(b.pages)||!b.pages.every(p=>typeof p==='string')||typeof b.bytes!=='string')throw new Error('A cópia contém um livro inválido.');const bytes=Uint8Array.from(atob(b.bytes),c=>c.charCodeAt(0)).buffer;return {id:b.id,name:b.name,fileName:String(b.fileName||b.name+'.pdf'),pages:b.pages,bytes,created:Number(b.created)||Date.now(),ocrPages:Array.isArray(b.ocrPages)?b.ocrPages:[]};});
 const state=d.state.filter(s=>typeof s.id==='string'&&['bible','pdf'].includes(s.kind)&&typeof s.bookId==='string');
 const chats=d.chats.map(c=>{if(typeof c.id!=='string'||!Array.isArray(c.messages)||!c.messages.every(m=>['user','assistant'].includes(m.role)&&typeof m.text==='string'))throw new Error('A cópia contém uma conversa inválida.');return {id:c.id,bookId:String(c.bookId||''),ref:String(c.ref||''),messages:c.messages.map(m=>({role:m.role,text:m.text,date:Number(m.date)||0,model:String(m.model||'')}))};});
 if(!confirm('Restaurar esta cópia? Estudos com a mesma identificação serão substituídos.'))return;pauseReading();await db.restoreRecords({books,state,chats});await refreshPDFs();lastStudy=await db.get('state','last');updateResumeCard();$('settingsDialog').close();toast('Cópia restaurada. Toque em Retomar meu estudo.');
}

on('bibleTab','click',()=>selectSource('bible'));on('pdfTab','click',()=>selectSource('pdf'));
on('bibleBook','change',()=>chapterOptions(true));on('startChapter','change',()=>{verseOptions('start',true);if(Number($('endChapter').value)<Number($('startChapter').value)){$('endChapter').value=$('startChapter').value;verseOptions('end',true);}});on('endChapter','change',()=>verseOptions('end',true));
on('openBible','click',()=>{const b=selectedBible();return activate({kind:'bible',bookId:b.id,startChapter:Number($('startChapter').value),startVerse:Number($('startVerse').value),endChapter:Number($('endChapter').value),endVerse:Number($('endVerse').value),title:`${b.name} ${$('startChapter').value}:${$('startVerse').value}–${$('endChapter').value}:${$('endVerse').value}`});});
on('playPause','click',()=>running?pauseReading():playReading());on('previous','click',()=>move(-1));on('next','click',()=>move(1));on('askButton','click',()=>openQuestion());on('sessionSummary','click',async()=>{await openQuestion({summary:true});await submitQuestion('Explique os principais pontos do intervalo estudado, em ordem, com as referências. Destaque os conceitos e eventuais ambiguidades.');});
on('studyMode','change',()=>savePosition(true));on('phoneFallback','click',()=>{speaker.usePhone=true;$('phoneFallback').hidden=true;updateVoiceLabel();return playReading();});
on('questionForm','submit',e=>{e.preventDefault();speaker.unlock();return submitQuestion($('questionInput').value);});on('explainAgain','click',()=>{speaker.unlock();return submitQuestion('Explique isso novamente com palavras ainda mais simples, mantendo o sentido do texto.');});on('giveExample','click',()=>{speaker.unlock();return submitQuestion('Dê um exemplo cotidiano para eu entender este ponto. Deixe claro que o exemplo é ilustrativo.');});on('dictate','click',dictation);on('cancelQuestion','click',()=>{stopQuestion();$('sendQuestion').textContent='Perguntar ao Gemini';toast('Resposta cancelada.');});on('stopAnswer','click',()=>speaker.stop());
on('resumeReading','click',()=>{stopQuestion();$('questionDialog').close();return playReading();});$('questionDialog').addEventListener('close',()=>{if(!running)stopQuestion();});
on('settingsButton','click',openSettings);on('settingsForm','submit',saveSettings);on('loadModels','click',loadAccountModels);on('showKey','click',()=>{$('apiKey').type=$('apiKey').type==='password'?'text':'password';$('showKey').textContent=$('apiKey').type==='password'?'Mostrar':'Ocultar';});
on('testVoice','click',async()=>{speaker.unlock();await speaker.say('Olá. Esta é a voz do aparelho. Vamos ler um trecho de cada vez.',{settingsOverride:{voiceMode:'phone',phoneVoice:$('phoneVoice').value,speechRate:Number($('speechRate').value)}});});
on('exportBackup','click',exportBackup);on('restoreBackup','change',e=>restoreBackup(e.target.files[0]));on('clearAudio','click',async()=>{await db.clear('audio');await storageInfo();toast('Áudios guardados removidos. Livros e conversas foram mantidos.');});
for(const button of document.querySelectorAll('[data-close]'))button.addEventListener('click',()=>$(button.dataset.close).close());$('settingsDialog').addEventListener('close',()=>speaker.stop());
on('pdfBook','change',pdfRangeChanged);
on('pdfFile','change',async e=>{const file=e.target.files[0];if(!file)return;pauseReading();$('importStatus').textContent='Abrindo o PDF…';$('pdfFile').disabled=true;try{const book=await importPDF(file,text=>$('importStatus').textContent=text);await db.put('books',book);await refreshPDFs(book.id);$('importStatus').textContent=`${book.pages.length} páginas adicionadas.${book.scanned?' Algumas páginas têm pouco texto; confira o original.':''}`;if(navigator.storage?.persist)void navigator.storage.persist();}catch(err){$('importStatus').textContent=err.name==='PasswordException'?'Este PDF está protegido por senha. Salve uma cópia desbloqueada e adicione novamente.':err.message;}finally{$('pdfFile').disabled=false;$('pdfFile').value='';}});
on('openPdf','click',()=>{const book=pdfBooks.find(b=>b.id===$('pdfBook').value);if(!book)return;return activate({kind:'pdf',bookId:book.id,startPage:Number($('pdfStart').value),endPage:Number($('pdfEnd').value),title:`${book.name} · páginas ${$('pdfStart').value}–${$('pdfEnd').value}`});});
on('deletePdf','click',async()=>{const id=$('pdfBook').value;if(!id||!confirm('Remover este PDF deste aparelho? Você precisará adicionar o arquivo novamente para voltar a lê-lo.'))return;if(study?.bookId===id)pauseReading();await db.remove('books',id);await refreshPDFs();toast('PDF removido deste aparelho.');});
$('originalPanel').addEventListener('toggle',()=>{if($('originalPanel').open)void showOriginal().catch(e=>notice(e.message,true));});
on('recognizePage','click',async()=>{if(!apiKey){openSettings();toast('Adicione uma chave Gemini para reconhecer esta página.');return;}pauseReading();const page=units[index].page;$('recognizePage').disabled=true;$('recognizePage').textContent='Reconhecendo…';try{const canvas=document.createElement('canvas');await renderPage(activeBook,page,canvas,1600);const text=await recognize({key:apiKey,model:cfg.textModel,image:canvas.toDataURL('image/jpeg',.88).split(',')[1]});activeBook.pages[page-1]=text;activeBook.ocrPages??=[];if(!activeBook.ocrPages.includes(page))activeBook.ocrPages.push(page);await db.put('books',activeBook);units=pdfUnits(activeBook,study.startPage,study.endPage);index=units.findIndex(u=>u.page===page);mark={};renderedStart=-1;renderReader();await savePosition(true);notice('Texto reconhecido por IA. Confira a página original: o reconhecimento pode conter erros.');}finally{$('recognizePage').disabled=false;$('recognizePage').textContent='Reconhecer esta página com Gemini';}});
on('lastStudy','click',async()=>{if(lastStudy){const saved={...lastStudy};selectSource(saved.kind);await activate(saved,{restore:true});}});
window.speechSynthesis?.addEventListener?.('voiceschanged',listPhoneVoices);
window.addEventListener('pagehide',()=>{if(running)pauseReading();speaker.stop();});
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(running)pauseReading();speaker.stop();}else if(running)void keepScreen();});
function connectionState(){$('offlineBadge').hidden=navigator.onLine;}
window.addEventListener('offline',connectionState);window.addEventListener('online',connectionState);
let installPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('installButton').hidden=false;});on('installButton','click',async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;$('installButton').hidden=true;}});

async function boot(){
 document.documentElement.style.setProperty('--reader-size',cfg.fontSize+'px');connectionState();
 if(location.protocol==='file:'){notice('Abra o aplicativo pelo endereço do GitHub Pages. O arquivo index.html aberto diretamente não ativa o leitor nem a instalação. Consulte COMECAR.html.',true);return;}
 const response=await fetch('./data/biblia.json');if(!response.ok)throw new Error('Não foi possível carregar a Bíblia. Confira se a pasta data foi enviada ao GitHub.');bible=await response.json();
 fillSelect($('bibleBook'),bible.books.map(b=>({value:b.id,label:b.name})),bible.books.find(b=>b.name==='João')?.id||bible.books[0].id);chapterOptions(true);
 await db.openDB();await refreshPDFs();const saved=await db.get('state','last');if(saved){lastStudy=saved;try{selectSource(saved.kind);await activate(saved,{restore:true});}catch{lastStudy=saved;const b=selectedBible();await activate({kind:'bible',bookId:b.id,startChapter:1,startVerse:1,endChapter:1,endVerse:Math.min(18,b.chapters[0].length),title:`${b.name} 1:1–18`});}}else{const b=selectedBible();$('endVerse').value=Math.min(18,b.chapters[0].length);await activate({kind:'bible',bookId:b.id,startChapter:1,startVerse:1,endChapter:1,endVerse:Number($('endVerse').value),title:`${b.name} 1:1–${$('endVerse').value}`});}
 if('serviceWorker'in navigator){try{const reg=await navigator.serviceWorker.register('./sw.js');reg.addEventListener('updatefound',()=>{const next=reg.installing;next?.addEventListener('statechange',()=>{if(next.state==='installed'&&navigator.serviceWorker.controller)toast('Atualização pronta. Feche e reabra o aplicativo quando terminar a leitura.');});});}catch{notice('O navegador não ativou o uso sem internet. A leitura online continua disponível.');}}
 registerTools();
}
function registerTools(){
 const ctx=document.modelContext;if(!ctx?.registerTool)return;
 const entries=[{name:'livro_claro_read_position',title:'Consultar ponto da leitura',description:'Lê o livro, trecho e posição selecionados. Não revela chave, arquivos nem conversas.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>({title:study?.title,reference:units[index]?.ref,playing:running,complete:completed})},{name:'livro_claro_open_bible_range',title:'Abrir trecho da Bíblia',description:'Abre um intervalo da Bíblia Livre, sem iniciar áudio ou enviar conteúdo ao Gemini.',inputSchema:{type:'object',properties:{bookId:{type:'string'},startChapter:{type:'integer',minimum:1},startVerse:{type:'integer',minimum:1},endChapter:{type:'integer',minimum:1},endVerse:{type:'integer',minimum:1}},required:['bookId','startChapter','startVerse','endChapter','endVerse'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{const b=bible.books.find(b=>b.id===input.bookId);if(!b)throw new Error('Livro não encontrado.');bibleUnits(b,input.startChapter,input.startVerse,input.endChapter,input.endVerse);await activate({kind:'bible',bookId:b.id,startChapter:input.startChapter,startVerse:input.startVerse,endChapter:input.endChapter,endVerse:input.endVerse,title:`${b.name} ${input.startChapter}:${input.startVerse}–${input.endChapter}:${input.endVerse}`});return {reference:units[index].ref,parts:units.length};}}];
 for(const t of entries)try{Promise.resolve(ctx.registerTool(t)).catch(()=>{});}catch{}
}
boot().catch(e=>{notice(e.message||'Não foi possível abrir o aplicativo neste navegador.',true);$('readingTitle').textContent='Vamos preparar sua leitura';});
